yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание ноаой записи
    path('create/', views.post_create, name='post_create'),
    # Редактирование записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(), name='password_change'),
    path(
        'password_change/done',
        PasswordChangeDoneView.as_view(), name='password_change_done'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls'))
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, blank=False)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group, blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ["-pub_date"]

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {'text': 'Текст поста', 'group': 'Группа'}
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
# from django.core.mail import send_mail

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView (TemplateView):
    template_name = 'about/author.html'


class AboutTechView (TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import redirect, render, get_object_or_404
from .forms import PostForm
from .models import Post, Group, User
from .utils import page_list


def index(request):
    """Главная страница."""

    post_list = Post.objects.select_related('author', 'group')
    page_obj = page_list(post_list, request)
    return render(request, 'posts/index.html', {'page_obj': page_obj})


def group_posts(request, slug):
    """вывод записей одной из групп. """

    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author', 'group')
    page_obj = page_list(posts, request)
    return render(request, 'posts/group_list.html', {'group': group,
                                                     'page_obj': page_obj})


def profile(request, username):
    """вывод списка всех записей пользователя. """

    user = get_object_or_404(User, username=username)
    post_list = user.posts.select_related('author')
    page_obj = page_list(post_list, request)
    return render(request, 'posts/profile.html', {
        'author': user,
        'page_obj': page_obj
    })


def post_detail(request, post_id):
    """подробная информация о записи. """

    post = get_object_or_404(Post, pk=post_id)
    return render(
        request,
        'posts/post_detail.html',
        {'post_detail': post}
    )


@login_required
def post_create(request):
    """добавление новой записи в базу. """

    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """редактирование записи. """

    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    return render(
        request,
        'posts/create_post.html',
        {
            'form': form,
            'is_edit': True,
            'post_id': post_id
        }
    )

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>{% block title %}заглушка{% endblock title %}</title>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">    
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </div>
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<!-- Использованы классы бустрапа: -->
<!-- border-top: создаёт тонкую линию сверху блока -->
<!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
<!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/form_errors.html
{% if form.errors %}
{% for field in form %}
  {% for error in field.errors %}            
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}

yatube/templates/includes/form_template.html
                {% load user_filters %}
                {% for field in form %}
                  <div class="form-group row my-3 p-3"
                    {% if field.field.required %} 
                      aria-required="true"
                    {% else %}
                      aria-required="false"
                    {% endif %}>

                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                  </div>
              {% endfor %}

yatube/templates/includes/header.html
{% load static %}
<header>
  <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color:red">Ya</span>tube</a>
        {% with request.resolver_match.view_name as view_name %} 
        <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {%  if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'password_change' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user}}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}
        </ul>
        {% endwith %}
    </div>
  </nav>      
</header>

yatube/templates/includes/posts_card.html
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
  <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
  </ul>
  <p>{{ post.text }}</p>
</article>
{% if post.group %} 
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
{% endif %}
{% if post.group %}
<br>
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}
{% if not forloop.last %}<hr>{% endif %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать пост
{% else %}
  Новый пост
{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать пост
                {% else %}
                  Добавить запись
                {% endif %}         
              </div>
              <div class="card-body">        
                {% if is_edit %}
                  <form method="post" action="{% url 'posts:post_edit' post_id %} ">
                {% else %}
                  <form method="post" action="{% url 'posts:post_create' %} ">
                {% endif %}
                {% csrf_token %}
                {% include 'includes/form_errors.html' %}
                {% include 'includes/form_template.html' %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}   
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
    {% endblock %}
    

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} {{group}} {% endblock %}
{% block content %}
<h1>{{ group }}</h1>
<p>{{ group.description }}</p>
  {% for post in page_obj %}
      {% include 'includes/posts_card.html' %}
  {% endfor %}
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
<h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
      {% include 'includes/posts_card.html' %}
  {% endfor %}
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/paginator.html
    {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              Предыдущая
            </a>
          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              Следующая
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              Последняя
            </a>
          </li>
        {% endif %}    
      </ul>
    </nav>
    {% endif %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post_detail.text.title|truncatechars:30}}{% endblock %}
{% block content %}

<div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post_detail.pub_date|date:"d E Y" }} 
        </li>
        <!-- если у поста есть группа -->
        {% if post_detail.group %}   
          <li class="list-group-item">
            Группа: {{ post_detail.group.title }}
            <br>
            <a href="{% url 'posts:group_list' post_detail.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post_detail.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post_detail.author.posts.count }}</span>
        </li>
        {% if post_detail.group %}
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post_detail.author %}">все посты пользователя</a>
        </li>
        {% endif %}
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>{{ post_detail.text }}</p>
      {% if post_detail.author == request.user %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post_detail.id %}"> 
        редактировать запись
      </a>
      {% endif %}
    </article>
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профиль пользователя {{ author }} {% endblock %}
{% block content %}
<h1>Все посты пользователя {{ author }}</h1>
<h3>Всего постов: {{ author.posts.count }} </h3>   
  {% for post in page_obj %}
      {% include 'includes/posts_card.html' %}
  {% endfor %}
  <!-- под последним постом нет линии -->
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/form_errors.html' %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}
          {% include 'includes/form_template.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% load user_filters %} {# Загружаем фильтры #}
            {% include 'includes/form_errors.html' %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% include 'includes/form_template.html' %}
              <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}